### ISSUE TITLE
Testing Issue itemes

### ISSUE THREAD

**Issue by KenMikkalson** [crimson30/Cardczar#1]
Testing

**Comment by KenMikkalson** [comment]
How do you add Labels?

**Comment by crimson30** [comment]
Beats me.

**Comment by KenMikkalson** [comment]
@crimson30 https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

Can you do this for our project? or maybe give me permissions to try and edit labels

**Comment by KenMikkalson** [comment]
Closing issue @crimson30 @sbholle @rjhGithub
